### ISSUE TITLE
New React (16.5.2) breaks react-coinbase-commerce library

### ISSUE THREAD

**Issue by Sm00g15** [coinbase/react-coinbase-commerce#11]
Just a heads up, if you install the new version of Create-React-App and try and use this library it will break it. I have found the fix though. 

In this portion of the code: 
`.amd?define("react-coinbase-commerce",["React"],t)`

delete `["React"]` and it will work.

**Comment by tysonbattistella** [comment]
@Sm00g15 I'm unable to recreate this issue, is it something you're still encountering?

**Comment by tysonbattistella** [comment]
Closing for now, feel free to reopen the issue if you're still encountering it.

**Comment by Sm00g15** [comment]
yeah, just tested it and I'm still getting that error on the newest version of React

**Comment by Sm00g15** [comment]
but the solution still holds true.
