### ISSUE TITLE
New payment cannot be made until last payment is successful

### ISSUE THREAD

**Issue by Sm00g15** [coinbase/react-coinbase-commerce#14]
**Problem:** 
I'm not able to make a new payment until the current payment being processed is successful. 

**Situation:**
I'm building a web app where users will click the React-Coinbase-Commerce button and pay. After the payment has been received the modal will be closed and they'll be able to continue on shopping. If the user finds another item they'd like to buy they can click the React-Coinbase-Commerce button again and a new charge should be created so they can buy this item as well. Instead when they click the button again the second time it just shows the payment verification process.

**Steps to Recreate** 
1) Setup coinbase-commerce button 
2) Send an arbitrary payment to a checkout
3) close the modal when the payment is detected
4) try to re-open to modal by clicking the coinbase-commerce button again
5) instead of being shown a new charge, you'll be shown the verification process (or completion page) of the old transaction

**Comment by tysonbattistella** [comment]
Thanks for the feedback! We've added the option to disable transaction state caching in version 1.3.0
