### ISSUE TITLE
Unknown DOM property allowtransparency

### ISSUE THREAD

**Issue by yummyelin** [coinbase/react-coinbase-commerce#15]
When I click the `CoinbaseCommerceButton` for the first time, console prints the following warning.
![image](https://user-images.githubusercontent.com/3782817/46824420-a2a59c00-cd45-11e8-8b0f-52a4005b112d.png)

Click for the second time, there is no warning.

Could you take a look at it?

**Comment by tysonbattistella** [comment]
Issue fixed in v1.3.1
