### ISSUE TITLE
onChargeSuccess prop is not working

### ISSUE THREAD

**Issue by Sm00g15** [coinbase/react-coinbase-commerce#20]
```
<CoinbaseCommerceButton
                      checkoutId="12a69b79-11bc-420b-a22c-06a17fdd72qf"
                      styled={true}
                      onLoad={() => this.props.modalBody("modalBody")}
                      disableCaching={true}
                      onChargeSuccess={res => {
                        console.log(res);
                        axios
                          .post("/chargesuccess", res)
                          .then(console.log("success"))
                          .catch(err => console.error(err));
                      }}
                      onModalClosed={() => this.props.modalBody("")}
                      customMetadata={`${this.state.email};${
                        this.props.parcelId
                      }`}
                      onPaymentDetected={res => {
                        console.log(res);
                        document
                          .querySelector(".coinbase-commerce-iframe-container")
                          .remove();
                        this.props.modalBody("");
                        this.setState({
                          paymentDetected:
                            "A Payment Has Been Detected. We will email you when the payment has been completed."
                        });
                        axios
                          .post("/chargedetected", res)
                          .then(console.log("success"))
                          .catch(err => console.error(err));
                      }}
                    >
```

Here is my component.

**Expected behavior:** 

I expect to get data posted to my endpoint when the charge successfully goes through

**Actual behavior:**

I get a data posted to my endpoint upon detection of the payment, but I don't receieve any response whenever the payment has successfully gone through.

**Comment by guacamoli** [comment]
Hey @Sm00g15, onPaymentDetected and onChargeSuccess are invoked from the iframe inside ".coinbase-commerce-iframe-container". I see that you are **removing the ".coinbase-commerce-iframe-container" when onPaymentDetected is invoked -- this is why onChargeSuccess is not invoked.** 

If you don't remove it, then onChargeSuccess should be called when the charge successfully goes through. Alternatively, you can add [webhooks](https://commerce.coinbase.com/docs/api/#webhooks) from the Dashboard Settings page (if you don't want to keep the container alive until the charge is successfully confirmed).

Hope this helps!

**Comment by Sm00g15** [comment]
AHA! awesome! Thanks so much

**Comment by Sm00g15** [comment]
hey @guacamoli how can I toggle the modal closed when the payment is detected while still keeping the iFrame available so that I can receieve a success alert from the onChargeSucess prop?
