### ISSUE TITLE
Unknown event handler property `onModalClosed`

### ISSUE THREAD

**Issue by donald-stolz** [coinbase/react-coinbase-commerce#23]
Hi,
I've been getting this error recently:
`Warning: Unknown event handler property `onModalClosed`. It will be ignored.`

Any idea what that could be related to?

**Comment by oa-coinbase** [comment]
Hey there, I'm closing this issue since it's been open for a long time. Feel free to open a new one if you're still having any issues.

**Comment by devcodeash** [comment]
Any solution for this issue

**Comment by nidzovito** [comment]
`onModalClosed` works even it throws the warning.
