### ISSUE TITLE
Refused to display iframe url

### ISSUE THREAD

**Issue by hbc19** [coinbase/react-coinbase-commerce#38]
Whenever I am clicking the button for payment, getting an error - 
Refused to display 'https://commerce.coinbase.com/embed/charges/f765421f2-1451-fafb-a513-aac6c819fba9?origin=http%3A%2F%2Flocalhost%3A3000&version=1.4.0&buttonId=bd4cec21-437d-41e1-a1dc-a0767325b757&cacheDisabled=undefined' in a frame because it set 'X-Frame-Options' to 'deny'.

Please help to solve this problem

**Comment by MiLeung** [comment]
If you are using `chargeId={chargeId}`, try using `chargeId={chargeCode}`. That's what worked for me

**Comment by oa-coinbase** [comment]
Hey there, that should be the right answer ^^^ I'll go ahead and close this issue since it's been open for a long time. Feel free to open a new one if you're still having issues!
