### ISSUE TITLE
Typescript Support

### ISSUE THREAD

**Issue by ConorOkus** [coinbase/react-coinbase-commerce#44]
Hi guys,

Nice component, any plans to support Typescript?

Thanks

**Comment by oa-coinbase** [comment]
@ConorOkus No plans currently, but feel free to submit a PR for it! :)

**Comment by osdiab** [comment]
i'd like this too! might contribute later, we're integrating it onto our site, if i get the time i'll write up some typings, test on our site and then PR here. i assume this project won't move to typescript so a flat `.d.ts` file is next best bet.
