### ISSUE TITLE
Unreviewed commit on master!

### ISSUE THREAD

**Issue by heimdall-asguard** [coinbase/react-coinbase-commerce#49]
Unreviewed commit(s) [COMPARE](https://github.com/coinbase/react-coinbase-commerce/compare/46a1865770f182c044cdefe3b2a882a2b93f6eee...876123bc49ed56cc8c3731414bb47b8fd7588b3a) was merged to master by sds.

Comment with appropriate number of :+1: to approve.

**Comment by heimdall-asguard** [comment]
Minimum Reviews      | 0/1
------------ | -------------






[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/react-coinbase-commerce&ref=876123bc49ed56cc8c3731414bb47b8fd7588b3a)

**Comment by sds** [comment]
👍

**Comment by heimdall-asguard** [comment]
Review Error for sds @ 2020-07-22 03:37:04 UTC
User cannot review their own pull request

**Comment by oa-coinbase** [comment]
👍

**Comment by heimdall-asguard** [comment]
Minimum Reviews      | 1/1
------------ | -------------
sds | 1



Pull request is reviewed and can be merged to master!

[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/react-coinbase-commerce&ref=876123bc49ed56cc8c3731414bb47b8fd7588b3a)
