### ISSUE TITLE
iframe content not loaded with chargeId ? 

### ISSUE THREAD

**Issue by CandyPopee** [coinbase/react-coinbase-commerce#5]
![coinbase](https://user-images.githubusercontent.com/16560990/45233005-b044ad80-b2d1-11e8-97d7-e36b24125845.jpeg)

**Comment by yi** [comment]
try using `charge.code`, that url in your screenshot is composite of `charge.id`. That url doesn't allow open in an iFrame by its web server.

**Comment by tysonbattistella** [comment]
@CandyPopee As @yi said, this should work if you use your charge's code. Let us know if this isn't working!

**Comment by ei08047** [comment]
This damm issue...Update documentation please, make this a better world.
