### ISSUE TITLE
"Element type is invalid" error when rendering button

### ISSUE THREAD

**Issue by rahulgi** [coinbase/react-coinbase-commerce#55]
Somewhere in the upgrade from version 1.4.4 to version 1.5.0, an error got introduced that causes the button to throw an error when rendering.

The error is: `Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.`.

Very simple [CodeSandbox](https://codesandbox.io/s/react-playground-forked-4v9m8?fontsize=14&hidenavigation=1&theme=dark). If you switch the `react-coinbase-commerce` version to 1.4.4 in the `package.json` file, you'll see the button start to work again.

**Comment by Ghorbanian** [comment]
> Somewhere in the upgrade from version 1.4.4 to version 1.5.0, an error got introduced that causes the button to throw an error when rendering.
> 
> The error is: `Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.`.
> 
> Very simple [CodeSandbox](https://codesandbox.io/s/react-playground-forked-4v9m8?fontsize=14&hidenavigation=1&theme=dark). If you switch the `react-coinbase-commerce` version to 1.4.4 in the `package.json` file, you'll see the button start to work again.

yup

**Comment by oa-coinbase** [comment]
Taking a look at this today, thanks for raising the issue! For now please keep on 1.4.4.

**Comment by oa-coinbase** [comment]
@rahulgi @Ghorbanian There was an issue with the webpack export and it should be fixed now in version 1.5.1.
