### ISSUE TITLE
Support for SSR

### ISSUE THREAD

**Issue by jdeanwaite** [coinbase/react-coinbase-commerce#6]
Hello Coinbase team! First of all, we at nobscrypto.com are loving Coinbase Commerce!

## Background
We use [GatsbyJS](https://next.gatsbyjs.org) (a static site generator built on React) which of course uses SSR to generate the static html. 

## Issue
This project [depends](https://github.com/coinbase/react-coinbase-commerce/blob/015aa37393f0714b29a153aa19278beebb54a833/src/components/IFrame.js) on `window` being defined. Of course, `window` only exists in the browser, so while building our production deployment using SSR, we are getting `window not defined` from this library.

## Solution
I believe the solution would be something as simple as a Polyfill. In fact, this issue went undetected for us because we were using a separate third-party library that brought in this type of polyfill already. It wasn't until we removed the other library that we ran into the issue with this library. You can see the polyfill used by this other library here:

https://github.com/aws-amplify/amplify-js/blob/66fa18db5e2d9450d467f3ed3d27994ed8aa0149/packages/core/src/Polyfills/Polyfills.ts

**Comment by guacamoli** [comment]
Thanks for reporting this. This is on our backlog but we likely won't be getting to it for a bit. Feel free to open up a PR if you have a clean solution.

**Comment by ksaitor** [comment]
Same problem!

**Comment by tysonbattistella** [comment]
This is fixed by #24 (Thanks @morleytatro)
