### ISSUE TITLE
Coinbase Commerce modal fails to load b/c X-Frame-Options header is set to DENY

### ISSUE THREAD

**Issue by rahulgi** [coinbase/react-coinbase-commerce#61]
The Commerce modal is failing to open because the Coinbase page it loads has the X-Frame-Options header set to deny.

![Screen Shot 2021-03-08 at 12 58 46 PM](https://user-images.githubusercontent.com/2237985/110381569-7ffb3880-800e-11eb-95a0-5f83e899e861.png)

**Comment by rahulgi** [comment]
Apologies, this was a bug on our end

**Comment by dabibu153** [comment]
its still not fixed:(
pls help

**Comment by yrombacatan** [comment]
up to this date
its hasn't been fixed?

**Comment by georgeportillo** [comment]
no fix yet huh
