### ISSUE TITLE
Coinbase login doesn't work in Safari or on iOS

### ISSUE THREAD

**Issue by rahulgi** [coinbase/react-coinbase-commerce#62]
Logging in via Coinbase doesn't seem to work in Safari on OSX nor Chrome or Safari on iOS. Choosing Coinbase as the payment method opens the Login popup, but even after logging in and authorizing Coinbase Commerce, the modal never picks up the authorization event and remains stuck on the "Just a moment, redirecting you to Coinbase..." screen.

Tested and the flow is working on Chrome on OSX and Android.

(53s) [loom video](https://www.loom.com/share/ab84c0ac60324bc798c933de70b6a69d) of issue

**Comment by rahulgi** [comment]
I just verified that the Coinbase Commerce flow on [givecrypto.org](https://www.givecrypto.org/donate/) (Brian Armstrong's nonprofit) also suffers from this issue, so I think it's a problem with Coinbase Commerce rather than our implementation.

**Comment by markulrich** [comment]
Same thing happens to me on givecrypto.org for Safari on OSX.
