### ISSUE TITLE
'X-Frams-Options' is set to 'Deny' when using chargeId in <CoinbaseCommerceButton> component

### ISSUE THREAD

**Issue by dabibu153** [coinbase/react-coinbase-commerce#63]
The error occurs when chargeId is used in the component
everything works fine for checkoutId

I need to generate payment charges with a dynamic amount. So I call API to generate a charge, send back the chargId which is then placed inside the button.

**Comment by MarcRoemmelt** [comment]
You can use the `Charge.code` instead of `Charge.id` and it should work

**Comment by dabibu153** [comment]
worked!!
