### ISSUE TITLE
No payment method available for recurring transactions

### ISSUE THREAD

**Issue by BETEP-ok** [coinbase/react-coinbase-commerce#7]
Hi, Team.
*please relocate the issue if wrongly placed*

Unfortunately when I try to create a recurring transaction on the web interface .
Message is displayed: "link and verify a payment method"even thou I have already 3 payment methods defined and verified.

can this be fixed ?

**Comment by tysonbattistella** [comment]
Please reach out to us at commerce@coinbase.com and someone will be able to help you out. I'll be closing this issue since it is unrelated to this repository
